#!/usr/bin/env python3
"""Generate the game-local libovr-openxr.toml configuration."""
import argparse
import secrets
from pathlib import Path


def generated_id() -> int:
    return secrets.randbelow(9_000_000_000_000_000_000) + 1


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate libovr-openxr.toml for an EchoVR installation"
    )
    parser.add_argument(
        "game_directory",
        type=Path,
        help="game root directory containing bin/win10",
    )
    parser.add_argument("--id", type=int, help="stable local user ID")
    parser.add_argument("--org-id", type=int, help="stable local organization ID")
    parser.add_argument("--oculus-id", help="local Oculus ID string")
    parser.add_argument(
        "--force", action="store_true", help="overwrite an existing configuration"
    )
    args = parser.parse_args()

    game_directory = args.game_directory.expanduser().resolve()
    win10 = game_directory / "bin" / "win10"
    if not win10.is_dir():
        parser.error(f"not an EchoVR game directory (missing {win10})")

    output = win10 / "libovr-openxr.toml"
    if output.exists() and not args.force:
        parser.error(f"{output} already exists; use --force to replace it")

    user_id = args.id if args.id is not None else generated_id()
    org_id = args.org_id if args.org_id is not None else user_id
    oculus_id = args.oculus_id or "OpenXRLocalUser"
    if user_id < 1 or org_id < 1:
        parser.error("--id and --org-id must be positive integers")
    if '"' in oculus_id or "\\" in oculus_id or "\n" in oculus_id:
        parser.error("--oculus-id must not contain quotes, backslashes, or newlines")

    output.write_text(
        "# Generated by libovr-openxr. Keep these values stable after linking.\n\n"
        "[user]\n"
        f"id = {user_id}\n"
        f"org_id = {org_id}\n"
        f'oculus_id = "{oculus_id}"\n',
        encoding="utf-8",
    )
    print(f"wrote {output}")
    print(f"user id: {user_id}")
    print(f"organization id: {org_id}")


if __name__ == "__main__":
    main()
